version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    target_branch: "main"
    default_reviewers:
    - mstark5652
    default_labels:
    - "security"
    - "dependabot"
    allowed_updates:
      - match:
          update_type: "security"